var euler = require('./euler');
var fs = require('fs');

/**
 * Multiples of 3 and 5
 * Problem 1
 *
 * If we list all the natural numbers below 10 that are multiples of 3 or 5, we get 3, 5, 6 and 9. The sum of these multiples is 23.
 * 
 * Find the sum of all the multiples of 3 or 5 below 1000.
 **/
function p1() {
    var multiples= euler.findMultiplesBelow(1000, 3, 5); var result = 0;
    for (var i in multiples) {
        result += multiples[i];
    }
    console.log(result);
}

/**
 * Even Fibonacci numbers
 * Problem 2
 *
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
 *
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 *
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
 **/
function p2() {
    var fibo = euler.buildFiboSequenceLessThan(4000000);
    var result = 0;
    for (var i in fibo) {
        if (euler.isEven(fibo[i])) {
            result += fibo[i];
        }
    }
    console.log(result);
}

/** 
 * Largest prime factor
 * Problem 3
 * 
 * The prime factors of 13195 are 5, 7, 13 and 29.
 * 
 * What is the largest prime factor of the number 600851475143 ?
 **/
function p3() {
    var largest = euler.findLargestPrimeFactorOf(600851475143);
    console.log(largest);
}

/**
 * Largest palindrome product
 * Problem 4
 * 
 * A palindromic number reads the same both ways. The largest palindrome made from the product of two 2-digit numbers is 9009 = 91 ¡Á 99.
 * 
 * Find the largest palindrome made from the product of two 3-digit numbers.
 **/
function p4() {
    var largest = 0;
    iloop:
    for (var i = 999; i >= 100; i--) {
        jloop:
        for (var j = 999; j >= 100; j--) {
            var multiply = i * j;
            var result = euler.isPalindrome(multiply);
            if (result) {
                if (largest < multiply) {
                    largest = multiply;
                    break jloop;
                }
            }
            if (multiply < largest) { 
                break jloop;
            }
        }
    }
    console.log("the largest palindrome: " + largest);
}

/**
 * Smallest multiple
 * Problem 5
 * 
 * 2520 is the smallest number that can be divided by each of the numbers from 1 to 10 without any remainder.
 * 
 * What is the smallest positive number that is evenly divisible by all of the numbers from 1 to 20?
 **/
function p5() {
    var array = [];
    for (var i = 0; i < 20; i++) {
        array[i] = i + 1;
    }
    var result = euler.findLeastCommonMultiple(array);
    console.log(result);
}

/**
 * Sum square difference
 * Problem 6
 * 
 * The sum of the squares of the first ten natural numbers is,
 * 1^2 + 2^2 + ... + 10^2 = 385
 * 
 * The square of the sum of the first ten natural numbers is,
 * (1 + 2 + ... + 10)^2 = 552 = 3025
 * 
 * Hence the difference between the sum of the squares of the first ten natural numbers and the square of the sum is 3025 ? 385 = 2640.
 * 
 * Find the difference between the sum of the squares of the first one hundred natural numbers and the square of the sum.
 **/
function p6() {
    var squareSum = 1/6 * 100 * (100 + 1) * (2 * 100 + 1);
    var sumSquare = 5050 * 5050;
    console.log(sumSquare - squareSum);
}

/**
 * 10001st prime
 * Problem 7
 * 
 * By listing the first six prime numbers: 2, 3, 5, 7, 11, and 13, we can see that the 6th prime is 13.
 * 
 * What is the 10 001st prime number?
 **/
function p7() {
    var index = 0;
    var result = 0;
    for (var n = 2; ; n++) {
        if (euler.isPrime(n)) {
            index++;
        }
        if (index == 10001) {
            result = n;
            break;
        }
    }
    console.log(n);
}

/**
 * Largest product in a series
 * Problem 8
 * 
 * Find the greatest product of five consecutive digits in the 1000-digit number.
 * 
 * 73167176531330624919225119674426574742355349194934
 * 96983520312774506326239578318016984801869478851843
 * 85861560789112949495459501737958331952853208805511
 * 12540698747158523863050715693290963295227443043557
 * 66896648950445244523161731856403098711121722383113
 * 62229893423380308135336276614282806444486645238749
 * 30358907296290491560440772390713810515859307960866
 * 70172427121883998797908792274921901699720888093776
 * 65727333001053367881220235421809751254540594752243
 * 52584907711670556013604839586446706324415722155397
 * 53697817977846174064955149290862569321978468622482
 * 83972241375657056057490261407972968652414535100474
 * 82166370484403199890008895243450658541227588666881
 * 16427171479924442928230863465674813919123162824586
 * 17866458359124566529476545682848912883142607690042
 * 24219022671055626321111109370544217506941658960408
 * 07198403850962455444362981230987879927244284909188
 * 84580156166097919133875499200524063689912560717606
 * 05886116467109405077541002256983155200055935729725
 * 71636269561882670428252483600823257530420752963450
 **/
function p8() {
    var input = 
        "73167176531330624919225119674426574742355349194934"+
        "96983520312774506326239578318016984801869478851843"+
        "85861560789112949495459501737958331952853208805511"+
        "12540698747158523863050715693290963295227443043557"+
        "66896648950445244523161731856403098711121722383113"+
        "62229893423380308135336276614282806444486645238749"+
        "30358907296290491560440772390713810515859307960866"+
        "70172427121883998797908792274921901699720888093776"+
        "65727333001053367881220235421809751254540594752243"+
        "52584907711670556013604839586446706324415722155397"+
        "53697817977846174064955149290862569321978468622482"+
        "83972241375657056057490261407972968652414535100474"+
        "82166370484403199890008895243450658541227588666881"+
        "16427171479924442928230863465674813919123162824586"+
        "17866458359124566529476545682848912883142607690042"+
        "24219022671055626321111109370544217506941658960408"+
        "07198403850962455444362981230987879927244284909188"+
        "84580156166097919133875499200524063689912560717606"+
        "05886116467109405077541002256983155200055935729725";
    var result = 0;
    for (var i = 0; i < input.length - 4; i++) {
        var product = 1;
        for (var j = 0; j < 5; j++) {
            product *= input[i + j];
        }
        if (result < product) {
            result = product;
        }
    }
    console.log("result: " + result);

}

/**
 * Special Pythagorean triplet
 * Problem 9
 * 
 * A Pythagorean triplet is a set of three natural numbers, a < b < c, for which,
 * a^2 + b^2 = c^2
 * 
 * For example, 3^2 + 4^2 = 9 + 16 = 25 = 5^2.
 * 
 * There exists exactly one Pythagorean triplet for which a + b + c = 1000.
 * Find the product abc.
 **/
function p9() {
    outer:
    for (var c = 6; ; c++) {
        for (var b = c - 1; b > 4; b--) {
            for (var a = b - 1; a > 3; a--) {
                if (a * a + b * b == c * c) {
                    var sum = a + b + c;
                    if (sum == 1000) {
                        console.log("result: " + a * b * c);
                        break outer;
                    }
                }
            }
        }
    }
}

/**
 * Summation of primes
 * Problem 10
 * 
 * The sum of the primes below 10 is 2 + 3 + 5 + 7 = 17.
 * 
 * Find the sum of all the primes below two million.
 **/
function p10() {
    var result = 0;
    for (var n = 2; n < 2000000; n++) {
        if (euler.isPrime(n)) {
            result += n;
        }
    }
    console.log(result);
}

/**
 * Largest product in a grid
 * Problem 11
 * 
 * In the 20×20 grid below, four numbers along a diagonal line have been marked in red.
 * 
 * 08 02 22 97 38 15 00 40 00 75 04 05 07 78 52 12 50 77 91 08
 * 49 49 99 40 17 81 18 57 60 87 17 40 98 43 69 48 04 56 62 00
 * 81 49 31 73 55 79 14 29 93 71 40 67 53 88 30 03 49 13 36 65
 * 52 70 95 23 04 60 11 42 69 24 68 56 01 32 56 71 37 02 36 91
 * 22 31 16 71 51 67 63 89 41 92 36 54 22 40 40 28 66 33 13 80
 * 24 47 32 60 99 03 45 02 44 75 33 53 78 36 84 20 35 17 12 50
 * 32 98 81 28 64 23 67 10 26 38 40 67 59 54 70 66 18 38 64 70
 * 67 26 20 68 02 62 12 20 95 63 94 39 63 08 40 91 66 49 94 21
 * 24 55 58 05 66 73 99 26 97 17 78 78 96 83 14 88 34 89 63 72
 * 21 36 23 09 75 00 76 44 20 45 35 14 00 61 33 97 34 31 33 95
 * 78 17 53 28 22 75 31 67 15 94 03 80 04 62 16 14 09 53 56 92
 * 16 39 05 42 96 35 31 47 55 58 88 24 00 17 54 24 36 29 85 57
 * 86 56 00 48 35 71 89 07 05 44 44 37 44 60 21 58 51 54 17 58
 * 19 80 81 68 05 94 47 69 28 73 92 13 86 52 17 77 04 89 55 40
 * 04 52 08 83 97 35 99 16 07 97 57 32 16 26 26 79 33 27 98 66
 * 88 36 68 87 57 62 20 72 03 46 33 67 46 55 12 32 63 93 53 69
 * 04 42 16 73 38 25 39 11 24 94 72 18 08 46 29 32 40 62 76 36
 * 20 69 36 41 72 30 23 88 34 62 99 69 82 67 59 85 74 04 36 16
 * 20 73 35 29 78 31 90 01 74 31 49 71 48 86 81 16 23 57 05 54
 * 01 70 54 71 83 51 54 69 16 92 33 48 61 43 52 01 89 19 67 48
 * 
 * The product of these numbers is 26 × 63 × 78 × 14 = 1788696.
 * 
 * What is the greatest product of four adjacent numbers in the same direction (up, down, left, right, or diagonally) in the 20×20 grid?
 **/
function p11() {
    var matrix =[ 
    [8,2,22,97,38,15,0,4,0,75,4,5,7,78,52,12,5,77,91,8],
    [49,49,99,4,17,81,18,57,6,87,17,4,98,43,69,48,4,56,62,0],
    [81,49,31,73,55,79,14,29,93,71,4,67,53,88,3,3,49,13,36,65],
    [52,7,95,23,4,6,11,42,69,24,68,56,1,32,56,71,37,2,36,91],
    [22,31,16,71,51,67,63,89,41,92,36,54,22,4,4,28,66,33,13,8],
    [24,47,32,6,99,3,45,2,44,75,33,53,78,36,84,2,35,17,12,5],
    [32,98,81,28,64,23,67,1,26,38,4,67,59,54,7,66,18,38,64,7],
    [67,26,2,68,2,62,12,2,95,63,94,39,63,8,4,91,66,49,94,21],
    [24,55,58,5,66,73,99,26,97,17,78,78,96,83,14,88,34,89,63,72],
    [21,36,23,9,75,0,76,44,2,45,35,14,0,61,33,97,34,31,33,95],
    [78,17,53,28,22,75,31,67,15,94,3,8,4,62,16,14,9,53,56,92],
    [16,39,5,42,96,35,31,47,55,58,88,24,0,17,54,24,36,29,85,57],
    [86,56,0,48,35,71,89,7,5,44,44,37,44,6,21,58,51,54,17,58],
    [19,8,81,68,5,94,47,69,28,73,92,13,86,52,17,77,4,89,55,4],
    [4,52,8,83,97,35,99,16,7,97,57,32,16,26,26,79,33,27,98,66],
    [88,36,68,87,57,62,2,72,3,46,33,67,46,55,12,32,63,93,53,69],
    [4,42,16,73,38,25,39,11,24,94,72,18,8,46,29,32,4,62,76,36],
    [2,69,36,41,72,3,23,88,34,62,99,69,82,67,59,85,74,4,36,16],
    [2,73,35,29,78,31,9,1,74,31,49,71,48,86,81,16,23,57,5,54],
    [1,7,54,71,83,51,54,69,16,92,33,48,61,43,52,1,89,19,67,48]
    ];
    var result = 0;
    // left -> right
    for (var i = 0; i < 20; i++) {
        for (var j = 0; j < 17; j++) {
            var product = 1;
            for (var k = 0; k < 4; k++) {
                product *= matrix[i][j+k];
            }
            result = result < product ? product : result;
        }
    }
    
    //up -> down
    for (var i = 0; i < 20; i++) {
        for (var j = 0; j < 17; j++) {
            var product = 1;
            for (var k = 0; k < 4; k++) {
                product *= matrix[j + k][i];
            }
            result = result < product ? product : result;
        }
    }

    //direction of "\"
    for (var i = 0; i < 17; i++) {
        for (var j = 0; j < 17 - i; j++) {
            var product1 = 1;
            for (var k = 0; k < 4; k++) {
                product1 *= matrix[i + j + k][j + k];
            }
            result = result < product1 ? product1 : result;
            var product2 = 1;
            for (var k = 0; k < 4; k++) {
               product2 *= matrix[j + k][i + j + k]; 
            }
            result = result < product2 ? product2 : result;
        }
    }

    //direction of "/"
    for (var i = 0; i < 17; i++) {
        for (var j = 0; j < 17 - i; j++) {
            var product1 = 1;
            for (var k = 0; k < 4; k++) {
                product1 *= matrix[j + k][19 - i - j - k];
            }
            result = result < product1 ? product1 : result;
            var product2 = 1;
            for (var k = 0; k < 4; k++) {
                product2 *= matrix[i + j + k][19 - k];
            }
            result = result < product2 ? product2 : result;
        }
    }
    console.log(result);
}

/**
 * Highly divisible triangular number
 * Problem 12
 * 
 * The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:
 * 
 * 1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...
 * 
 * Let us list the factors of the first seven triangle numbers:
 * 
 *      1: 1
 *      3: 1,3
 *      6: 1,2,3,6
 *      10: 1,2,5,10
 *      15: 1,3,5,15
 *      21: 1,3,7,21
 *      28: 1,2,4,7,14,28
 * 
 *      We can see that 28 is the first triangle number to have over five divisors.
 * 
 *      What is the value of the first triangle number to have over five hundred divisors?
 **/
function p12() {
    var divisors = 0;
    var number = 0;
    var index = 0;
    while (divisors <= 500) {
        number = euler.triangularNumberAt(index);
        var factors = euler.findFactorsOf(number);
        divisors = factors.length;
        index++;
    }
    console.log(number);
}

/**
 * Large sum
 * Problem 13
 * 
 * Work out the first ten digits of the sum of the following one-hundred 50-digit numbers.
 * 37107287533902102798797998220837590246510135740250
 * 46376937677490009712648124896970078050417018260538
 * 74324986199524741059474233309513058123726617309629
 * 91942213363574161572522430563301811072406154908250
 * 23067588207539346171171980310421047513778063246676
 * 89261670696623633820136378418383684178734361726757
 * 28112879812849979408065481931592621691275889832738
 * 44274228917432520321923589422876796487670272189318
 * 47451445736001306439091167216856844588711603153276
 * 70386486105843025439939619828917593665686757934951
 * 62176457141856560629502157223196586755079324193331
 * 64906352462741904929101432445813822663347944758178
 * 92575867718337217661963751590579239728245598838407
 * 58203565325359399008402633568948830189458628227828
 * 80181199384826282014278194139940567587151170094390
 * 35398664372827112653829987240784473053190104293586
 * 86515506006295864861532075273371959191420517255829
 * 71693888707715466499115593487603532921714970056938
 * 54370070576826684624621495650076471787294438377604
 * 53282654108756828443191190634694037855217779295145
 * 36123272525000296071075082563815656710885258350721
 * 45876576172410976447339110607218265236877223636045
 * 17423706905851860660448207621209813287860733969412
 * 81142660418086830619328460811191061556940512689692
 * 51934325451728388641918047049293215058642563049483
 * 62467221648435076201727918039944693004732956340691
 * 15732444386908125794514089057706229429197107928209
 * 55037687525678773091862540744969844508330393682126
 * 18336384825330154686196124348767681297534375946515
 * 80386287592878490201521685554828717201219257766954
 * 78182833757993103614740356856449095527097864797581
 * 16726320100436897842553539920931837441497806860984
 * 48403098129077791799088218795327364475675590848030
 * 87086987551392711854517078544161852424320693150332
 * 59959406895756536782107074926966537676326235447210
 * 69793950679652694742597709739166693763042633987085
 * 41052684708299085211399427365734116182760315001271
 * 65378607361501080857009149939512557028198746004375
 * 35829035317434717326932123578154982629742552737307
 * 94953759765105305946966067683156574377167401875275
 * 88902802571733229619176668713819931811048770190271
 * 25267680276078003013678680992525463401061632866526
 * 36270218540497705585629946580636237993140746255962
 * 24074486908231174977792365466257246923322810917141
 * 91430288197103288597806669760892938638285025333403
 * 34413065578016127815921815005561868836468420090470
 * 23053081172816430487623791969842487255036638784583
 * 11487696932154902810424020138335124462181441773470
 * 63783299490636259666498587618221225225512486764533
 * 67720186971698544312419572409913959008952310058822
 * 95548255300263520781532296796249481641953868218774
 * 76085327132285723110424803456124867697064507995236
 * 37774242535411291684276865538926205024910326572967
 * 23701913275725675285653248258265463092207058596522
 * 29798860272258331913126375147341994889534765745501
 * 18495701454879288984856827726077713721403798879715
 * 38298203783031473527721580348144513491373226651381
 * 34829543829199918180278916522431027392251122869539
 * 40957953066405232632538044100059654939159879593635
 * 29746152185502371307642255121183693803580388584903
 * 41698116222072977186158236678424689157993532961922
 * 62467957194401269043877107275048102390895523597457
 * 23189706772547915061505504953922979530901129967519
 * 86188088225875314529584099251203829009407770775672
 * 11306739708304724483816533873502340845647058077308
 * 82959174767140363198008187129011875491310547126581
 * 97623331044818386269515456334926366572897563400500
 * 42846280183517070527831839425882145521227251250327
 * 55121603546981200581762165212827652751691296897789
 * 32238195734329339946437501907836945765883352399886
 * 75506164965184775180738168837861091527357929701337
 * 62177842752192623401942399639168044983993173312731
 * 32924185707147349566916674687634660915035914677504
 * 99518671430235219628894890102423325116913619626622
 * 73267460800591547471830798392868535206946944540724
 * 76841822524674417161514036427982273348055556214818
 * 97142617910342598647204516893989422179826088076852
 * 87783646182799346313767754307809363333018982642090
 * 10848802521674670883215120185883543223812876952786
 * 71329612474782464538636993009049310363619763878039
 * 62184073572399794223406235393808339651327408011116
 * 66627891981488087797941876876144230030984490851411
 * 60661826293682836764744779239180335110989069790714
 * 85786944089552990653640447425576083659976645795096
 * 66024396409905389607120198219976047599490197230297
 * 64913982680032973156037120041377903785566085089252
 * 16730939319872750275468906903707539413042652315011
 * 94809377245048795150954100921645863754710598436791
 * 78639167021187492431995700641917969777599028300699
 * 15368713711936614952811305876380278410754449733078
 * 40789923115535562561142322423255033685442488917353
 * 44889911501440648020369068063960672322193204149535
 * 41503128880339536053299340368006977710650566631954
 * 81234880673210146739058568557934581403627822703280
 * 82616570773948327592232845941706525094512325230608
 * 22918802058777319719839450180888072429661980811197
 * 77158542502016545090413245809786882778948721859617
 * 72107838435069186155435662884062257473692284509516
 * 20849603980134001723930671666823555245252804609722
 * 53503534226472524250874054075591789781264330331690
 **/
function p13() {
    var numbers = [ 
    "37107287533902102798797998220837590246510135740250",
    "46376937677490009712648124896970078050417018260538",
    "74324986199524741059474233309513058123726617309629",
    "91942213363574161572522430563301811072406154908250",
    "23067588207539346171171980310421047513778063246676",
    "89261670696623633820136378418383684178734361726757",
    "28112879812849979408065481931592621691275889832738",
    "44274228917432520321923589422876796487670272189318",
    "47451445736001306439091167216856844588711603153276",
    "70386486105843025439939619828917593665686757934951",
    "62176457141856560629502157223196586755079324193331",
    "64906352462741904929101432445813822663347944758178",
    "92575867718337217661963751590579239728245598838407",
    "58203565325359399008402633568948830189458628227828",
    "80181199384826282014278194139940567587151170094390",
    "35398664372827112653829987240784473053190104293586",
    "86515506006295864861532075273371959191420517255829",
    "71693888707715466499115593487603532921714970056938",
    "54370070576826684624621495650076471787294438377604",
    "53282654108756828443191190634694037855217779295145",
    "36123272525000296071075082563815656710885258350721",
    "45876576172410976447339110607218265236877223636045",
    "17423706905851860660448207621209813287860733969412",
    "81142660418086830619328460811191061556940512689692",
    "51934325451728388641918047049293215058642563049483",
    "62467221648435076201727918039944693004732956340691",
    "15732444386908125794514089057706229429197107928209",
    "55037687525678773091862540744969844508330393682126",
    "18336384825330154686196124348767681297534375946515",
    "80386287592878490201521685554828717201219257766954",
    "78182833757993103614740356856449095527097864797581",
    "16726320100436897842553539920931837441497806860984",
    "48403098129077791799088218795327364475675590848030",
    "87086987551392711854517078544161852424320693150332",
    "59959406895756536782107074926966537676326235447210",
    "69793950679652694742597709739166693763042633987085",
    "41052684708299085211399427365734116182760315001271",
    "65378607361501080857009149939512557028198746004375",
    "35829035317434717326932123578154982629742552737307",
    "94953759765105305946966067683156574377167401875275",
    "88902802571733229619176668713819931811048770190271",
    "25267680276078003013678680992525463401061632866526",
    "36270218540497705585629946580636237993140746255962",
    "24074486908231174977792365466257246923322810917141",
    "91430288197103288597806669760892938638285025333403",
    "34413065578016127815921815005561868836468420090470",
    "23053081172816430487623791969842487255036638784583",
    "11487696932154902810424020138335124462181441773470",
    "63783299490636259666498587618221225225512486764533",
    "67720186971698544312419572409913959008952310058822",
    "95548255300263520781532296796249481641953868218774",
    "76085327132285723110424803456124867697064507995236",
    "37774242535411291684276865538926205024910326572967",
    "23701913275725675285653248258265463092207058596522",
    "29798860272258331913126375147341994889534765745501",
    "18495701454879288984856827726077713721403798879715",
    "38298203783031473527721580348144513491373226651381",
    "34829543829199918180278916522431027392251122869539",
    "40957953066405232632538044100059654939159879593635",
    "29746152185502371307642255121183693803580388584903",
    "41698116222072977186158236678424689157993532961922",
    "62467957194401269043877107275048102390895523597457",
    "23189706772547915061505504953922979530901129967519",
    "86188088225875314529584099251203829009407770775672",
    "11306739708304724483816533873502340845647058077308",
    "82959174767140363198008187129011875491310547126581",
    "97623331044818386269515456334926366572897563400500",
    "42846280183517070527831839425882145521227251250327",
    "55121603546981200581762165212827652751691296897789",
    "32238195734329339946437501907836945765883352399886",
    "75506164965184775180738168837861091527357929701337",
    "62177842752192623401942399639168044983993173312731",
    "32924185707147349566916674687634660915035914677504",
    "99518671430235219628894890102423325116913619626622",
    "73267460800591547471830798392868535206946944540724",
    "76841822524674417161514036427982273348055556214818",
    "97142617910342598647204516893989422179826088076852",
    "87783646182799346313767754307809363333018982642090",
    "10848802521674670883215120185883543223812876952786",
    "71329612474782464538636993009049310363619763878039",
    "62184073572399794223406235393808339651327408011116",
    "66627891981488087797941876876144230030984490851411",
    "60661826293682836764744779239180335110989069790714",
    "85786944089552990653640447425576083659976645795096",
    "66024396409905389607120198219976047599490197230297",
    "64913982680032973156037120041377903785566085089252",
    "16730939319872750275468906903707539413042652315011",
    "94809377245048795150954100921645863754710598436791",
    "78639167021187492431995700641917969777599028300699",
    "15368713711936614952811305876380278410754449733078",
    "40789923115535562561142322423255033685442488917353",
    "44889911501440648020369068063960672322193204149535",
    "41503128880339536053299340368006977710650566631954",
    "81234880673210146739058568557934581403627822703280",
    "82616570773948327592232845941706525094512325230608",
    "22918802058777319719839450180888072429661980811197",
    "77158542502016545090413245809786882778948721859617",
    "72107838435069186155435662884062257473692284509516",
    "20849603980134001723930671666823555245252804609722",
    "53503534226472524250874054075591789781264330331690"];
    console.log(euler.add(numbers));
}

/**
 * Longest Collatz sequence
 * Problem 14
 * 
 * The following iterative sequence is defined for the set of positive integers:
 * 
 * n ¡ú n/2 (n is even)
 * n ¡ú 3n + 1 (n is odd)
 * 
 * Using the rule above and starting with 13, we generate the following sequence:
 * 13 ¡ú 40 ¡ú 20 ¡ú 10 ¡ú 5 ¡ú 16 ¡ú 8 ¡ú 4 ¡ú 2 ¡ú 1
 * 
 * It can be seen that this sequence (starting at 13 and finishing at 1) contains 10 terms. Although it has not been proved yet (Collatz Problem), it is thought that all starting numbers finish at 1.
 * 
 * Which starting number, under one million, produces the longest chain?
 * 
 * NOTE: Once the chain starts the terms are allowed to go above one million.
 **/
function p14() {
    var max = 0;
    var result = 0;
    for (var i = 1; i < 1000000; i++) {
        var number = i;
        var sequenceLength = 1;
        while (number > 1) {
            if (euler.isEven(number)) {
                number /= 2;
            } else {
                number = 3 * number + 1;
            }
            sequenceLength++;
        }
        if (max < sequenceLength) {
            max = sequenceLength;
            result = i;
        }
    }
    console.log(result + " with chain length: " + max);
}

/**
 * Lattice paths
 * Problem 15
 * 
 * Starting in the top left corner of a 2×2 grid, and only being able to move to the right and down, there are exactly 6 routes to the bottom right corner.
 * 
 * How many such routes are there through a 20×20 grid?
 **/
function p15() {
    var path = visit2(0, 0, 20, 20);
    console.log(path);
}

function visit2(i, j, x, y) {
    var path = 0;
    if (i < x && j < y) {
        path = visit2(i + 1, j, x, y) + visit2(i, j + 1, x, y);
    } else if (i < x || j < y) {
        path = 1;
    }

    return path;
}

/**
 * Power digit sum
 * Problem 16
 * 
 * 215 = 32768 and the sum of its digits is 3 + 2 + 7 + 6 + 8 = 26.
 * 
 * What is the sum of the digits of the number 21000?
 **/
function p16() {
    var digitLut = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9];
    var result = euler.pow(2, 1000);
    var start = "0";
    var sum = 0;
    for (var i = 0; i < result.length; i++) {
        var digit = digitLut[result[i] - start];
        sum += digit;
    }
    console.log(result + " with sum of the digits: " + sum);
}

/**
 * Number letter counts
 * Problem 17
 * 
 * If the numbers 1 to 5 are written out in words: one, two, three, four, five, then there are 3 + 3 + 5 + 4 + 4 = 19 letters used in total.
 * 
 * If all the numbers from 1 to 1000 (one thousand) inclusive were written out in words, how many letters would be used?
 * 
 * NOTE: Do not count spaces or hyphens. For example, 342 (three hundred and forty-two) contains 23 letters and 115 (one hundred and fifteen) contains 20 letters. The use of "and" when writing out numbers is in compliance with British usage.
 **/
function p17() {
    var letters = 0;
    for (var i = 1; i < 1000; i++) {
        letters += calculateLetters(i);
    }
    letters += "onethousand".length;
    console.log(letters);
}

var one = ["one", "two", "three", "four", "five", "six", "seven", "eight", "nine"];
var two = ["ten", "eleven", "twelve", "thirteen", "fourteen", "fifteen", "sixteen", "seventeen", "eighteen", "nineteen"];
var ten = ["ten", "twenty", "thirty", "forty", "fifty", "sixty", "seventy", "eighty", "ninety"];
var hundred = "hundred"; 
function calculateLetters(n) {
    var letters = 0;
    if (n == 0) {
        return 0;
    } else if (n < 10) {
        return one[n - 1].length;
    } else if (n >= 10 && n < 20) {
        return two[n - 10].length;
    } else if (n >= 20 && n < 100) {
        var n1 = n % 10;
        var l1 = calculateLetters(n1);
        var n2 = (n - n1) / 10;
        var l2 = ten[n2 - 1].length;
        return l1 + l2;
    } else if (n >= 100 && n < 1000) {
        var n1 = n % 100;
        var l1 = calculateLetters(n1);
        var n2 = (n - n1) / 100;
        var l2 = one[n2 - 1].length + hundred.length;
        l2 = (n1 != 0) ? (l2 + 3) : l2;
        return l1 + l2;
    }
}

/**
 * Maximum path sum I
 * Problem 18
 * 
 * By starting at the top of the triangle below and moving to adjacent numbers on the row below, the maximum total from top to bottom is 23.
 * 
 * 3
 * 7 4
 * 2 4 6
 * 8 5 9 3
 * 
 * That is, 3 + 7 + 4 + 9 = 23.
 * 
 * Find the maximum total from top to bottom of the triangle below:
 * 
 * 75
 * 95 64
 * 17 47 82
 * 18 35 87 10
 * 20 04 82 47 65
 * 19 01 23 75 03 34
 * 88 02 77 73 07 63 67
 * 99 65 04 28 06 16 70 92
 * 41 41 26 56 83 40 80 70 33
 * 41 48 72 33 47 32 37 16 94 29
 * 53 71 44 65 25 43 91 52 97 51 14
 * 70 11 33 28 77 73 17 78 39 68 17 57
 * 91 71 52 38 17 14 91 43 58 50 27 29 48
 * 63 66 04 68 89 53 67 30 73 16 69 87 40 31
 * 04 62 98 27 23 09 70 98 73 93 38 53 60 04 23
 * 
 * NOTE: As there are only 16384 routes, it is possible to solve this problem by trying every route. However, Problem 67, is the same challenge with a triangle containing one-hundred rows; it cannot be solved by brute force, and requires a clever method! ;o)
 **/ 
function p18() {
    var paths = [];
    var numbers = 
//        [
//        [3],
//        [7, 4],
//        [2, 4, 6],
//        [8, 5, 9, 3]];
        [
        [75],
        [95,64],
        [17,47,82],
        [18,35,87,10],
        [20,04,82,47,65],
        [19,01,23,75,03,34],
        [88,02,77,73,07,63,67],
        [99,65,04,28,06,16,70,92],
        [41,41,26,56,83,40,80,70,33],
        [41,48,72,33,47,32,37,16,94,29],
        [53,71,44,65,25,43,91,52,97,51,14],
        [70,11,33,28,77,73,17,78,39,68,17,57],
        [91,71,52,38,17,14,91,43,58,50,27,29,48],
        [63,66,04,68,89,53,67,30,73,16,69,87,40,31],
        [04,62,98,27,23,09,70,98,73,93,38,53,60,04,23]
        ];
    for (var i = 0; i < numbers.length; i++) {
        paths[i] = []
        for (var j = 0; j < numbers[i].length; j++) {
            paths[i][j] = numbers[i][j];
        }
    }
    visitTriangleArray(numbers, paths);
}

function visitTriangleArray(unsettled, settled) {
    for (var i = 0; i < unsettled.length - 1; i++) {
        for (var j = 0; j < unsettled[i].length; j++) {
            var n1 = settled[i][j] + unsettled[i + 1][j];
            var n2 = settled[i][j] + unsettled[i + 1][j + 1];
            if (settled[i + 1][j] > unsettled[i + 1][j]) {
                settled[i + 1][j] = (settled[i + 1][j] < n1) ? n1 : settled[i + 1][j];
            } else {
                settled[i + 1][j] = n1;
            }
            
            if (settled[i + 1][j + 1] > unsettled[i + 1][j + 1]) {
                settled[i + 1][j + 1] = (settled[i + 1][j + 1] < n2) ? n2 : settled[i + 1][j + 1];
            } else {
                settled[i + 1][j + 1] = n2;
            }
        }
    }
    console.log(Math.max.apply(Math, settled[settled.length - 1]));
}

/**
 * Counting Sundays
 * Problem 19
 * 
 * You are given the following information, but you may prefer to do some research for yourself.
 * 
 *     1 Jan 1900 was a Monday.
 *     Thirty days has September,
 *     April, June and November.
 *     All the rest have thirty-one,
 *     Saving February alone,
 *     Which has twenty-eight, rain or shine.
 *     And on leap years, twenty-nine.
 *     A leap year occurs on any year evenly divisible by 4, but not on a century unless it is divisible by 400.
 * 
 * How many Sundays fell on the first of the month during the twentieth century (1 Jan 1901 to 31 Dec 2000)?
 **/
function p19() {
    var start = 2;
    var total = 0;
    var monthDays = [31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31];
    for (var i = 1901; i <= 2000; i++) {
        for (var j = 0; j < 12; j++) {
            var days = monthDays[j];
            if (j == 1 && isLeapYear(i)) {
                days++;
            }
            start += days % 7;
            if (start == 7) {
                if (i != 2000 || j != 11) {
                    total++;
                } 
            }
            if (start > 7) {
                start %= 7;
            }
        }
    }

    console.log(total);
}

function isLeapYear(year) {
    if (year % 100 == 0) {
        return year % 400 == 0;
    } else {
        return year % 4 == 0;
    }
}

/**
 * Factorial digit sum
 * Problem 20
 * 
 * n! means n ¡Á (n ? 1) ¡Á ... ¡Á 3 ¡Á 2 ¡Á 1
 * 
 * For example, 10! = 10 ¡Á 9 ¡Á ... ¡Á 3 ¡Á 2 ¡Á 1 = 3628800,
 * and the sum of the digits in the number 10! is 3 + 6 + 2 + 8 + 8 + 0 + 0 = 27.
 * 
 * Find the sum of the digits in the number 100!
 **/
function p20() {
    var digitLut = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9];
    var result = euler.factorial(100);
    var start = "0"; var sum = 0; for (var i = 0; i < result.length; i++) { var digit = digitLut[result[i] - start];
        sum += digit;
    }
    console.log(result + " with sum of the digits: " + sum);
}

/**
 * Amicable numbers
 * Problem 21
 * 
 * Let d(n) be defined as the sum of proper divisors of n (numbers less than n which divide evenly into n).
 * If d(a) = b and d(b) = a, where a ¿ b, then a and b are an amicable pair and each of a and b are called amicable numbers.
 * 
 * For example, the proper divisors of 220 are 1, 2, 4, 5, 10, 11, 20, 22, 44, 55 and 110; therefore d(220) = 284. The proper divisors of 284 are 1, 2, 4, 71 and 142; so d(284) = 220.
 * 
 * Evaluate the sum of all the amicable numbers under 10000.
 **/
function p21() {
    var amicables = [];
    var index = 0;
    for (var i = 2; i < 10000; i++) {
        if (!euler.isPrime(i) && !euler.isIn(i, amicables)) {
            var sum1 = d(i);
            var sum2 = d(sum1);
            if (sum2 == i && sum1 != i) {
                amicables[index++] = i;
                amicables[index++] = sum1;
            }
        }
    }
    var sum = 0;
    for (var i in amicables) {
        sum += amicables[i];
    }
    console.log(amicables);
    console.log(sum);
}

function d(n) {
    var sum = 0;
    var factors = euler.findFactorsOf(n);
    for (var i = 0; i < factors.length; i++) {
        if (factors[i] < n) {
            sum += factors[i];
        }
    }

    return sum;
}

/**
 * By starting at the top of the triangle below and moving to adjacent numbers on the row below, the maximum total from top to bottom is 23.
 * 
 * 3
 * 7 4
 * 2 4 6
 * 8 5 9 3
 * 
 * That is, 3 + 7 + 4 + 9 = 23.
 * 
 * Find the maximum total from top to bottom in triangle.txt (right click and 'Save Link/Target As...'), a 15K text file containing a triangle with one-hundred rows.
 * 
 * NOTE: This is a much more difficult version of Problem 18. It is not possible to try every route to solve this problem, as there are 299 altogether! If you could check one trillion (1012) routes every second it would take over twenty billion years to check them all. There is an efficient algorithm to solve it. ;o)
 **/ 
function p67() {
    var lines = fs.readFileSync('triangle.txt').toString().split("\n");
    var unsettled= [], settled = [];
    for (var i = 0; i < lines.length - 1; i++) {
        var numbers = lines[i].split(" ");
        unsettled[i] = [];
        settled[i] = [];
        for (var j = 0; j < numbers.length; j++) {
            unsettled[i][j] = parseInt(numbers[j]);
            settled[i][j] = parseInt(numbers[j]);
        }
    }
    visitTriangleArray(unsettled, settled);
}

var start = new Date();
p21();
var end = new Date();
var elapsed = end - start;
console.log("elapsed time: " + elapsed);
